### ISSUE TITLE
Disable JMeter's console logging

### ISSUE THREAD

**Issue by ttomtsis** [ttomtsis/icarus#11]
JMeter's intense logging clutters the output console of the application when executing

**Comment by vignesh-kg** [comment]
Hi,

You can setup logging level in your application.yml like this

logging:
  level:
    org: INFO
#  jmeter: OFF (here specify JMeter's root package)    

just specify JMeter's root package and change it's level to either WARN or OFF.
logging level OFF will not log anything.
